<?php

namespace Database\Seeders;

use App\Models\Post;
use App\Models\PostBoard;
use Illuminate\Database\Seeder;

class PostSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $postBoards = PostBoard::all();
        
        $posts = [
            [
                'external_id' => 'linkedin_001',
                'post_board_id' => $postBoards->where('name', 'LinkedIn Jobs')->first()->id,
                'title' => 'Senior Full Stack Developer',
                'description' => 'We are looking for a Senior Full Stack Developer to join our growing team. You will be responsible for building and maintaining scalable web applications using modern technologies like React, Node.js, and AWS. The ideal candidate will have 5+ years of experience in full-stack development and a passion for clean, maintainable code.',
                'company_name' => 'TechCorp Inc.',
                'company_website' => 'https://techcorp.com',
                'location' => 'San Francisco, CA',
                'is_remote' => true,
                'post_type' => 'full-time',
                'experience_level' => 'senior',
                'salary_min' => 140000,
                'salary_max' => 180000,
                'salary_currency' => 'USD',
                'salary_period' => 'year',
                'skills' => ['JavaScript', 'TypeScript', 'React', 'Node.js', 'AWS', 'PostgreSQL', 'Docker'],
                'categories' => ['Engineering', 'Full Stack', 'Web Development'],
                'apply_url' => 'https://techcorp.com/careers/senior-developer',
                'post_url' => 'https://linkedin.com/jobs/view/senior-developer',
                'posted_at' => now()->subDays(2),
                'expires_at' => now()->addDays(30),
                'is_active' => true
            ],
            [
                'external_id' => 'indeed_001',
                'post_board_id' => $postBoards->where('name', 'Indeed')->first()->id,
                'title' => 'Data Scientist',
                'description' => 'Join our data science team to build machine learning models and analyze large datasets. You will work on predictive analytics, customer segmentation, and recommendation systems. Experience with Python, TensorFlow, and big data technologies required.',
                'company_name' => 'DataTech Solutions',
                'company_website' => 'https://datatech.com',
                'location' => 'New York, NY',
                'is_remote' => true,
                'post_type' => 'full-time',
                'experience_level' => 'mid',
                'salary_min' => 110000,
                'salary_max' => 150000,
                'salary_currency' => 'USD',
                'salary_period' => 'year',
                'skills' => ['Python', 'R', 'SQL', 'TensorFlow', 'PyTorch', 'Pandas', 'Apache Spark'],
                'categories' => ['Data Science', 'Machine Learning', 'Analytics'],
                'apply_url' => 'https://datatech.com/careers/data-scientist',
                'post_url' => 'https://indeed.com/jobs/data-scientist',
                'posted_at' => now()->subDays(1),
                'expires_at' => now()->addDays(45),
                'is_active' => true
            ],
            [
                'external_id' => 'stackoverflow_001',
                'post_board_id' => $postBoards->where('name', 'Stack Overflow Jobs')->first()->id,
                'title' => 'Frontend Developer (React)',
                'description' => 'We are seeking a talented Frontend Developer to join our team. You will be responsible for building user interfaces using React and modern JavaScript. Experience with TypeScript, Redux, and responsive design is a plus.',
                'company_name' => 'WebFlow Solutions',
                'company_website' => 'https://webflow.com',
                'location' => 'Austin, TX',
                'is_remote' => true,
                'post_type' => 'full-time',
                'experience_level' => 'mid',
                'salary_min' => 90000,
                'salary_max' => 130000,
                'salary_currency' => 'USD',
                'salary_period' => 'year',
                'skills' => ['JavaScript', 'TypeScript', 'React', 'Redux', 'CSS', 'HTML', 'Git'],
                'categories' => ['Frontend', 'React', 'Web Development'],
                'apply_url' => 'https://webflow.com/careers/frontend-developer',
                'post_url' => 'https://stackoverflow.com/jobs/frontend-developer',
                'posted_at' => now()->subDays(3),
                'expires_at' => now()->addDays(25),
                'is_active' => true
            ],
            [
                'external_id' => 'glassdoor_001',
                'post_board_id' => $postBoards->where('name', 'Glassdoor')->first()->id,
                'title' => 'UX/UI Designer',
                'description' => 'Join our design team to create beautiful and intuitive user experiences. You will work on user research, wireframing, prototyping, and visual design. Experience with Figma, user testing, and design systems required.',
                'company_name' => 'Design Studio Pro',
                'company_website' => 'https://designstudiopro.com',
                'location' => 'San Francisco, CA',
                'is_remote' => true,
                'post_type' => 'full-time',
                'experience_level' => 'mid',
                'salary_min' => 85000,
                'salary_max' => 120000,
                'salary_currency' => 'USD',
                'salary_period' => 'year',
                'skills' => ['Figma', 'Sketch', 'Adobe Creative Suite', 'User Research', 'Prototyping'],
                'categories' => ['Design', 'UX/UI', 'User Experience'],
                'apply_url' => 'https://designstudiopro.com/careers/ux-designer',
                'post_url' => 'https://glassdoor.com/jobs/ux-designer',
                'posted_at' => now()->subDays(5),
                'expires_at' => now()->addDays(35),
                'is_active' => true
            ],
            [
                'external_id' => 'angel_001',
                'post_board_id' => $postBoards->where('name', 'AngelList Talent')->first()->id,
                'title' => 'DevOps Engineer',
                'description' => 'Join our early-stage startup to build and maintain our cloud infrastructure. You will work with AWS, Kubernetes, and CI/CD pipelines. Experience with infrastructure as code and monitoring required.',
                'company_name' => 'CloudTech Solutions',
                'company_website' => 'https://cloudtech.com',
                'location' => 'Seattle, WA',
                'is_remote' => true,
                'post_type' => 'full-time',
                'experience_level' => 'mid',
                'salary_min' => 120000,
                'salary_max' => 160000,
                'salary_currency' => 'USD',
                'salary_period' => 'year',
                'skills' => ['AWS', 'Kubernetes', 'Docker', 'Terraform', 'Jenkins', 'Python', 'Bash'],
                'categories' => ['DevOps', 'Infrastructure', 'Cloud'],
                'apply_url' => 'https://cloudtech.com/careers/devops-engineer',
                'post_url' => 'https://angel.co/jobs/devops-engineer',
                'posted_at' => now()->subDays(1),
                'expires_at' => now()->addDays(20),
                'is_active' => true
            ],
            [
                'external_id' => 'weworkremotely_001',
                'post_board_id' => $postBoards->where('name', 'WeWorkRemotely')->first()->id,
                'title' => 'Product Manager',
                'description' => 'Lead product strategy and development for our B2B SaaS platform. You will work with cross-functional teams to define product requirements, conduct user research, and drive product launches.',
                'company_name' => 'ProductCorp',
                'company_website' => 'https://productcorp.com',
                'location' => 'Remote',
                'is_remote' => true,
                'post_type' => 'full-time',
                'experience_level' => 'senior',
                'salary_min' => 130000,
                'salary_max' => 180000,
                'salary_currency' => 'USD',
                'salary_period' => 'year',
                'skills' => ['Product Strategy', 'Agile/Scrum', 'User Research', 'Data Analysis', 'SQL'],
                'categories' => ['Product Management', 'Strategy', 'SaaS'],
                'apply_url' => 'https://productcorp.com/careers/product-manager',
                'post_url' => 'https://weworkremotely.com/jobs/product-manager',
                'posted_at' => now()->subDays(2),
                'expires_at' => now()->addDays(30),
                'is_active' => true
            ],
            [
                'external_id' => 'dribbble_001',
                'post_board_id' => $postBoards->where('name', 'Dribbble Jobs')->first()->id,
                'title' => 'Senior Product Designer',
                'description' => 'Join our design team to create exceptional user experiences. You will lead design projects, conduct user research, and create comprehensive design systems. Experience with design systems and user testing required.',
                'company_name' => 'Creative Agency',
                'company_website' => 'https://creativeagency.com',
                'location' => 'New York, NY',
                'is_remote' => true,
                'post_type' => 'full-time',
                'experience_level' => 'senior',
                'salary_min' => 100000,
                'salary_max' => 140000,
                'salary_currency' => 'USD',
                'salary_period' => 'year',
                'skills' => ['Figma', 'Sketch', 'Adobe Creative Suite', 'User Research', 'Design Systems'],
                'categories' => ['Design', 'Product Design', 'UX/UI'],
                'apply_url' => 'https://creativeagency.com/careers/senior-designer',
                'post_url' => 'https://dribbble.com/jobs/senior-designer',
                'posted_at' => now()->subDays(4),
                'expires_at' => now()->addDays(40),
                'is_active' => true
            ],
            [
                'external_id' => 'builtin_001',
                'post_board_id' => $postBoards->where('name', 'Built In')->first()->id,
                'title' => 'Backend Developer (Python)',
                'description' => 'Build scalable backend services using Python and Django. You will work on API development, database design, and system architecture. Experience with PostgreSQL, Redis, and cloud platforms required.',
                'company_name' => 'Tech Startup',
                'company_website' => 'https://techstartup.com',
                'location' => 'Boston, MA',
                'is_remote' => true,
                'post_type' => 'full-time',
                'experience_level' => 'mid',
                'salary_min' => 95000,
                'salary_max' => 130000,
                'salary_currency' => 'USD',
                'salary_period' => 'year',
                'skills' => ['Python', 'Django', 'PostgreSQL', 'Redis', 'AWS', 'Docker'],
                'categories' => ['Backend', 'Python', 'API Development'],
                'apply_url' => 'https://techstartup.com/careers/backend-developer',
                'post_url' => 'https://builtin.com/jobs/backend-developer',
                'posted_at' => now()->subDays(1),
                'expires_at' => now()->addDays(25),
                'is_active' => true
            ],
            [
                'external_id' => 'linkedin_002',
                'post_board_id' => $postBoards->where('name', 'LinkedIn Jobs')->first()->id,
                'title' => 'Machine Learning Engineer',
                'description' => 'Join our ML team to build and deploy machine learning models at scale. You will work on recommendation systems, natural language processing, and predictive analytics. Experience with TensorFlow, PyTorch, and MLOps required.',
                'company_name' => 'AI Innovations',
                'company_website' => 'https://aiinnovations.com',
                'location' => 'San Francisco, CA',
                'is_remote' => true,
                'post_type' => 'full-time',
                'experience_level' => 'senior',
                'salary_min' => 150000,
                'salary_max' => 200000,
                'salary_currency' => 'USD',
                'salary_period' => 'year',
                'skills' => ['Python', 'TensorFlow', 'PyTorch', 'Kubernetes', 'Docker', 'AWS', 'MLOps'],
                'categories' => ['Machine Learning', 'AI', 'Engineering'],
                'apply_url' => 'https://aiinnovations.com/careers/ml-engineer',
                'post_url' => 'https://linkedin.com/jobs/view/ml-engineer',
                'posted_at' => now()->subDays(3),
                'expires_at' => now()->addDays(35),
                'is_active' => true
            ],
            [
                'external_id' => 'indeed_002',
                'post_board_id' => $postBoards->where('name', 'Indeed')->first()->id,
                'title' => 'Full Stack Developer (Vue.js)',
                'description' => 'Build modern web applications using Vue.js and Node.js. You will work on both frontend and backend development, with a focus on user experience and performance. Experience with Vue 3, TypeScript, and cloud platforms preferred.',
                'company_name' => 'Web Solutions Inc.',
                'company_website' => 'https://websolutions.com',
                'location' => 'Austin, TX',
                'is_remote' => true,
                'post_type' => 'full-time',
                'experience_level' => 'mid',
                'salary_min' => 85000,
                'salary_max' => 120000,
                'salary_currency' => 'USD',
                'salary_period' => 'year',
                'skills' => ['Vue.js', 'TypeScript', 'Node.js', 'PostgreSQL', 'AWS', 'Docker'],
                'categories' => ['Full Stack', 'Vue.js', 'Web Development'],
                'apply_url' => 'https://websolutions.com/careers/full-stack-developer',
                'post_url' => 'https://indeed.com/jobs/full-stack-developer',
                'posted_at' => now()->subDays(2),
                'expires_at' => now()->addDays(30),
                'is_active' => true
            ]
        ];

        foreach ($posts as $post) {
            Post::create($post);
        }
    }
} 